### ISSUE TITLE
Release 1.1.0 Broke Build Pipelines

### ISSUE THREAD

**Issue by alexanderepstein** [sarugaku/resolvelib#174]
Installing `pymssql` from source 
With the following in pyproject.toml section

```text
[tool.pdm.resolution]
respect-source-order = true
no-binary = ["pymssql"]
```

Using pdm version: `2.18.2`
Same error on both Mac/Linux

```text
  ✖ Install pymssql 2.3.1 failed
ERRORS:
add pymssql failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 
228, in install_candidate
    self.manager.install(can)
  File "/usr/local/lib/python3.11/site-packages/pdm/installers/manager.py", line
33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/models/candidates.py", line 
411, in build
    self._cached = Path(builder.build(build_dir, 
metadata_directory=self._metadata_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/builders/base.py", line 84, 
in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/builders/wheel.py", line 23,
in build
    self.install(self._requires, shared=True)
  File "/usr/local/lib/python3.11/site-packages/pdm/builders/base.py", line 322,
in install
    install_requirements(missing, env)
  File "/usr/local/lib/python3.11/site-packages/pdm/installers/core.py", line 
29, in install_requirements
    resolved, _ = resolve(resolver, reqs, max_rounds=resolve_max_rounds, 
keep_self=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/resolver/core.py", line 43, 
in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/resolvelib/resolvers/resolution.py", 
line 515, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/resolvelib/resolvers/resolution.py", 
line 440, in resolve
    name = min(narrowed_unstatisfied_names, key=self._get_preference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/resolvelib/resolvers/resolution.py", 
line 173, in _get_preference
    return self._p.get_preference(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/resolver/providers.py", line
112, in get_preference
    dep_depth = min(parent_depths, default=0) + 1
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/resolver/providers.py", line
109, in <genexpr>
    self._known_depth if parent is not None else 0
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'setuptools-scm'
  0:00:39 ✖ Some package operations failed. 1/1
See /root/.local/state/pdm/log/pdm-install-4cx7vf9r.log for detailed debug log.
```

**Comment by notatallshaw** [comment]
Thanks for reporting, but this looks like it should be reported to pdm, at least first, to see if they are using resolvelib in an unexpected/unsupported way, or if this is a genuine bug on resolvelib side.

**Comment by alexanderepstein** [comment]
So I hadn't updated pdm, but in my CI/CD since this package wasn't pinned by my application it was downloading the latest version (regardless of version of pdm). This has been fine since resolvelib hasnt been updated since last year, but once this was released all of my builds broke.  If I manually just downgraded this package to 1.0.1 with pip then pymyssql installs successfully.

It could be that pdm was/is using this package incorrectly (upgrading pdm to latest in the link you have there still has this issue) and the symptom only showed up when resolvelib was updated. I am going to make a dup over in pdm issues though as you could be right that the issue lies with them.

**Comment by alexanderepstein** [comment]
I tried updating to 2.20.0 for pdm but then I get a pdm specific error with that release around some incorrect type hinting

```
    class BaseProvider(AbstractProvider[Requirement, Candidate, str]):
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'AbstractProvider' is not subscriptable
```

So I cant test that out to see if it resolves the issue

**Comment by alexanderepstein** [comment]
https://github.com/sarugaku/resolvelib/issues/174

**Comment by notatallshaw** [comment]
> I tried updating to 2.20.0 for pdm but then I get a pdm specific error with that release around some incorrect type hinting

Seems like someone else has already reported that error: https://github.com/pdm-project/pdm/issues/3241, looks like this wasn't tested for Python 3.8.

**Comment by frostming** [comment]
That is not resolvelib problem, closing it now.
