### ISSUE TITLE
KeyError: 'dictionary is empty' during backtracking

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/resolvelib#47]
Quoting @pradyunsg from https://python.zulipchat.com/#narrow/stream/218659-pip-development/topic/Resolvelib.20question/near/195392774

```py
spec = """\
A 1.0.0
    B == 1.0.0
A 2.0.0
    B == 2.0.0
    C == 1.0.0
A 3.0.0
    B == 3.0.0
    C == 2.0.0
B 1.0.0
    C == 1.0.0
B 2.0.0
    C == 2.0.0
B 3.0.0
    C == 3.0.0
# C 1.0.0
C 2.0.0
C 3.0.0
"""
```

I'm seeing an exception in `_backtrack`, and I'm not sure if the issue is with the resolver logic or with the provider at hand:

```pytb
 Traceback (most recent call last):
  File "examples/reporter_demo.py", line 101, in <module>
    result = resolver.resolve([("A", SpecifierSet(">=1.0"))])
  File "resolvelib/resolvers.py", line 414, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "resolvelib/resolvers.py", line 315, in resolve
    result = self._backtrack()
  File "resolvelib/resolvers.py", line 257, in _backtrack
    name, candidate = self._states.pop().mapping.popitem()
KeyError: 'dictionary is empty'
```

**Comment by uranusjr** [comment]
Fixed in #62.
